### ISSUE TITLE
Try method

### ISSUE THREAD

**Issue by Hau-Hau** [jscarle/LightResults#13]
Hi, do you plan to implement any equivalent of [Try(...) method from FluentResults](https://github.com/altmann/FluentResults/blob/8b675de7e8b6e4c0921e95138c99e15fd52cde40/src/FluentResults/Factories/Results.cs#L234)?
It is simple wrapper, however I think it would be nice to have it out of the box.

**Comment by jscarle** [comment]
You mean for exception handling?

**Comment by Hau-Hau** [comment]
Yes, exactly.

**Comment by jscarle** [comment]
Hey @Hau-Hau,

Give this a try and let me know:
https://www.nuget.org/packages/LightResults.Extensions.ExceptionHandling

**Comment by Hau-Hau** [comment]
I have took a look on the code and how it works.
Funcs and Actions works great. However the Try(...) extension method is not available on any class members, as extension methods works only on delegates.

So, in case below we cannot use `Try` extension method.
```csharp
    class Program
    {
        public static void Main()
        {
            var result = Add.Try(1, 1);
        }

        public static int Add(int? a, int? b)
        {
            if (a is null) throw new ArgumentNullException(nameof(a));
            if (b is null) throw new ArgumentNullException(nameof(b));
            return (int)(a + b);
        }
    }
```

I was thinking about problem and probably we don't want to extend Result type in any way, especially as you are introduced this convenient extensions packages.

Unfortunately C# is not allowing to add static extension methods.
One of solutions to solve this issue would be additional Try class. However, I have to admit that it is not that elegant solution like extension methods.


e.g.
```csharp
    public static class Try
    {
        public static Result Execute(Action action)
        {
            try
            {
                action();
                return Result.Ok();
            }
            catch (Exception ex)
            {
                return Result.Fail(ex.Message);
            }
        }

        public static Result<TResult> Execute<TResult>(this Func<TResult> func)
        {
            try
            {
                return Result<TResult>.Ok(func());
            }
            catch (Exception ex)
            {
                return Result.Fail<TResult>(ex.Message);
            }
        }
    }
```

Second potential solution which personally I prefer would need to mark Result as partial.
With that modifier we would be able to extend Result class and make a bit more convenient API. I'm not sure how it would impact performance.

```csharp
public partial class Result
{
    public static Result Execute(Action action)
    {
        try
        {
            action();
            return Result.Ok();
        }
        catch (Exception ex)
        {
            return Result.Fail(ex.Message);
        }
    }
  
    public static Result<TResult> Execute<TResult>(Func<TResult> func)
    {
        try
        {
            return Result<TResult>.Ok(func());
        }
        catch (Exception ex)
        {
            return Result.Fail<TResult>(ex.Message);
        }
    }
}
```

**Comment by jscarle** [comment]
If you add `using static LightResults.Extensions.ExceptionHandling.ExceptionHandler;` with the rest of your using statements at the top of your file, you can then do `Try(Method, args)` as such:

```csharp
using static LightResults.Extensions.ExceptionHandling.ExceptionHandler;

public static class Program
{
    public static void Main()
    {
        var result = Try(Add, 1, 1);
    }

    public static int Add(int? a, int? b)
    {
        if (a is null) throw new ArgumentNullException(nameof(a));
        if (b is null) throw new ArgumentNullException(nameof(b));
        return (int)(a + b);
    }
}
```

I also added this to the readme.

**Comment by Hau-Hau** [comment]
Works very well. Thanks!

**Comment by jscarle** [comment]
Glad to hear it!
